/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message_comms.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message_comms.pb-c.h"
void   client_movement_req__init
                     (ClientMovementReq         *message)
{
  static const ClientMovementReq init_value = CLIENT_MOVEMENT_REQ__INIT;
  *message = init_value;
}
size_t client_movement_req__get_packed_size
                     (const ClientMovementReq *message)
{
  assert(message->base.descriptor == &client_movement_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_movement_req__pack
                     (const ClientMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_movement_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_movement_req__pack_to_buffer
                     (const ClientMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_movement_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientMovementReq *
       client_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientMovementReq *)
     protobuf_c_message_unpack (&client_movement_req__descriptor,
                                allocator, len, data);
}
void   client_movement_req__free_unpacked
                     (ClientMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_movement_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_connection_req__init
                     (ClientConnectionReq         *message)
{
  static const ClientConnectionReq init_value = CLIENT_CONNECTION_REQ__INIT;
  *message = init_value;
}
size_t client_connection_req__get_packed_size
                     (const ClientConnectionReq *message)
{
  assert(message->base.descriptor == &client_connection_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_connection_req__pack
                     (const ClientConnectionReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_connection_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_connection_req__pack_to_buffer
                     (const ClientConnectionReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_connection_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientConnectionReq *
       client_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientConnectionReq *)
     protobuf_c_message_unpack (&client_connection_req__descriptor,
                                allocator, len, data);
}
void   client_connection_req__free_unpacked
                     (ClientConnectionReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_connection_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_movement_req__init
                     (ServerMovementReq         *message)
{
  static const ServerMovementReq init_value = SERVER_MOVEMENT_REQ__INIT;
  *message = init_value;
}
size_t server_movement_req__get_packed_size
                     (const ServerMovementReq *message)
{
  assert(message->base.descriptor == &server_movement_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_movement_req__pack
                     (const ServerMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_movement_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_movement_req__pack_to_buffer
                     (const ServerMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_movement_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerMovementReq *
       server_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerMovementReq *)
     protobuf_c_message_unpack (&server_movement_req__descriptor,
                                allocator, len, data);
}
void   server_movement_req__free_unpacked
                     (ServerMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_movement_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_connection_req__init
                     (ServerConnectionReq         *message)
{
  static const ServerConnectionReq init_value = SERVER_CONNECTION_REQ__INIT;
  *message = init_value;
}
size_t server_connection_req__get_packed_size
                     (const ServerConnectionReq *message)
{
  assert(message->base.descriptor == &server_connection_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_connection_req__pack
                     (const ServerConnectionReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_connection_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_connection_req__pack_to_buffer
                     (const ServerConnectionReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_connection_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerConnectionReq *
       server_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerConnectionReq *)
     protobuf_c_message_unpack (&server_connection_req__descriptor,
                                allocator, len, data);
}
void   server_connection_req__free_unpacked
                     (ServerConnectionReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_connection_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char client_movement_req__type__default_value[] = "MOVE";
static const ProtobufCFieldDescriptor client_movement_req__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, type),
    NULL,
    &client_movement_req__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, pass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dir",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, dir),
    &direction_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_movement_req__field_indices_by_name[] = {
  1,   /* field[1] = ch */
  3,   /* field[3] = dir */
  2,   /* field[2] = pass */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange client_movement_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor client_movement_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_movement_req",
  "ClientMovementReq",
  "ClientMovementReq",
  "",
  sizeof(ClientMovementReq),
  4,
  client_movement_req__field_descriptors,
  client_movement_req__field_indices_by_name,
  1,  client_movement_req__number_ranges,
  (ProtobufCMessageInit) client_movement_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char client_connection_req__type__default_value[] = "HELLO";
static const ProtobufCFieldDescriptor client_connection_req__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientConnectionReq, type),
    NULL,
    &client_connection_req__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_connection_req__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange client_connection_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_connection_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_connection_req",
  "ClientConnectionReq",
  "ClientConnectionReq",
  "",
  sizeof(ClientConnectionReq),
  1,
  client_connection_req__field_descriptors,
  client_connection_req__field_indices_by_name,
  1,  client_connection_req__number_ranges,
  (ProtobufCMessageInit) client_connection_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_movement_req__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerMovementReq, result),
    &move_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_movement_req__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange server_movement_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor server_movement_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "server_movement_req",
  "ServerMovementReq",
  "ServerMovementReq",
  "",
  sizeof(ServerMovementReq),
  1,
  server_movement_req__field_descriptors,
  server_movement_req__field_indices_by_name,
  1,  server_movement_req__number_ranges,
  (ProtobufCMessageInit) server_movement_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_connection_req__field_descriptors[3] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerConnectionReq, result),
    &connection_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerConnectionReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ServerConnectionReq, pass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_connection_req__field_indices_by_name[] = {
  1,   /* field[1] = name */
  2,   /* field[2] = pass */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange server_connection_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor server_connection_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "server_connection_req",
  "ServerConnectionReq",
  "ServerConnectionReq",
  "",
  sizeof(ServerConnectionReq),
  3,
  server_connection_req__field_descriptors,
  server_connection_req__field_indices_by_name,
  1,  server_connection_req__number_ranges,
  (ProtobufCMessageInit) server_connection_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction_enum__enum_values_by_number[4] =
{
  { "UP", "DIRECTION_ENUM__UP", 0 },
  { "DOWN", "DIRECTION_ENUM__DOWN", 1 },
  { "LEFT", "DIRECTION_ENUM__LEFT", 2 },
  { "RIGHT", "DIRECTION_ENUM__RIGHT", 3 },
};
static const ProtobufCIntRange direction_enum__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction_enum__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction_enum",
  "Direction_enum",
  "DirectionEnum",
  "",
  4,
  direction_enum__enum_values_by_number,
  4,
  direction_enum__enum_values_by_name,
  1,
  direction_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue move_result__enum_values_by_number[2] =
{
  { "OK", "MOVE_RESULT__OK", 0 },
  { "WALL", "MOVE_RESULT__WALL", 1 },
};
static const ProtobufCIntRange move_result__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex move_result__enum_values_by_name[2] =
{
  { "OK", 0 },
  { "WALL", 1 },
};
const ProtobufCEnumDescriptor move_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MoveResult",
  "MoveResult",
  "MoveResult",
  "",
  2,
  move_result__enum_values_by_number,
  2,
  move_result__enum_values_by_name,
  1,
  move_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue connection_result__enum_values_by_number[2] =
{
  { "CONN_OK", "CONNECTION_RESULT__CONN_OK", 0 },
  { "CONN_ERROR", "CONNECTION_RESULT__CONN_ERROR", 1 },
};
static const ProtobufCIntRange connection_result__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex connection_result__enum_values_by_name[2] =
{
  { "CONN_ERROR", 1 },
  { "CONN_OK", 0 },
};
const ProtobufCEnumDescriptor connection_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ConnectionResult",
  "ConnectionResult",
  "ConnectionResult",
  "",
  2,
  connection_result__enum_values_by_number,
  2,
  connection_result__enum_values_by_name,
  1,
  connection_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
