/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message_comms.proto */

#ifndef PROTOBUF_C_message_5fcomms_2eproto__INCLUDED
#define PROTOBUF_C_message_5fcomms_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct ClientMovementReq ClientMovementReq;
typedef struct ClientConnectionReq ClientConnectionReq;
typedef struct ServerMovementReq ServerMovementReq;
typedef struct ServerConnectionReq ServerConnectionReq;


/* --- enums --- */

typedef enum _DirectionEnum {
  DIRECTION_ENUM__UP = 0,
  DIRECTION_ENUM__DOWN = 1,
  DIRECTION_ENUM__LEFT = 2,
  DIRECTION_ENUM__RIGHT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIRECTION_ENUM)
} DirectionEnum;
typedef enum _MoveResult {
  MOVE_RESULT__OK = 0,
  MOVE_RESULT__WALL = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MOVE_RESULT)
} MoveResult;
typedef enum _ConnectionResult {
  CONNECTION_RESULT__CONN_OK = 0,
  CONNECTION_RESULT__CONN_ERROR = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CONNECTION_RESULT)
} ConnectionResult;

/* --- messages --- */

struct  ClientMovementReq
{
  ProtobufCMessage base;
  char *type;
  ProtobufCBinaryData ch;
  int32_t pass;
  DirectionEnum dir;
};
extern char client_movement_req__type__default_value[];
#define CLIENT_MOVEMENT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_movement_req__descriptor) \
, client_movement_req__type__default_value, {0,NULL}, 0, DIRECTION_ENUM__UP }


struct  ClientConnectionReq
{
  ProtobufCMessage base;
  char *type;
};
extern char client_connection_req__type__default_value[];
#define CLIENT_CONNECTION_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_connection_req__descriptor) \
, client_connection_req__type__default_value }


struct  ServerMovementReq
{
  ProtobufCMessage base;
  MoveResult result;
};
#define SERVER_MOVEMENT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_movement_req__descriptor) \
, MOVE_RESULT__OK }


struct  ServerConnectionReq
{
  ProtobufCMessage base;
  ConnectionResult result;
  ProtobufCBinaryData name;
  int32_t pass;
};
#define SERVER_CONNECTION_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_connection_req__descriptor) \
, CONNECTION_RESULT__CONN_OK, {0,NULL}, 0 }


/* ClientMovementReq methods */
void   client_movement_req__init
                     (ClientMovementReq         *message);
size_t client_movement_req__get_packed_size
                     (const ClientMovementReq   *message);
size_t client_movement_req__pack
                     (const ClientMovementReq   *message,
                      uint8_t             *out);
size_t client_movement_req__pack_to_buffer
                     (const ClientMovementReq   *message,
                      ProtobufCBuffer     *buffer);
ClientMovementReq *
       client_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_movement_req__free_unpacked
                     (ClientMovementReq *message,
                      ProtobufCAllocator *allocator);
/* ClientConnectionReq methods */
void   client_connection_req__init
                     (ClientConnectionReq         *message);
size_t client_connection_req__get_packed_size
                     (const ClientConnectionReq   *message);
size_t client_connection_req__pack
                     (const ClientConnectionReq   *message,
                      uint8_t             *out);
size_t client_connection_req__pack_to_buffer
                     (const ClientConnectionReq   *message,
                      ProtobufCBuffer     *buffer);
ClientConnectionReq *
       client_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_connection_req__free_unpacked
                     (ClientConnectionReq *message,
                      ProtobufCAllocator *allocator);
/* ServerMovementReq methods */
void   server_movement_req__init
                     (ServerMovementReq         *message);
size_t server_movement_req__get_packed_size
                     (const ServerMovementReq   *message);
size_t server_movement_req__pack
                     (const ServerMovementReq   *message,
                      uint8_t             *out);
size_t server_movement_req__pack_to_buffer
                     (const ServerMovementReq   *message,
                      ProtobufCBuffer     *buffer);
ServerMovementReq *
       server_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_movement_req__free_unpacked
                     (ServerMovementReq *message,
                      ProtobufCAllocator *allocator);
/* ServerConnectionReq methods */
void   server_connection_req__init
                     (ServerConnectionReq         *message);
size_t server_connection_req__get_packed_size
                     (const ServerConnectionReq   *message);
size_t server_connection_req__pack
                     (const ServerConnectionReq   *message,
                      uint8_t             *out);
size_t server_connection_req__pack_to_buffer
                     (const ServerConnectionReq   *message,
                      ProtobufCBuffer     *buffer);
ServerConnectionReq *
       server_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_connection_req__free_unpacked
                     (ServerConnectionReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ClientMovementReq_Closure)
                 (const ClientMovementReq *message,
                  void *closure_data);
typedef void (*ClientConnectionReq_Closure)
                 (const ClientConnectionReq *message,
                  void *closure_data);
typedef void (*ServerMovementReq_Closure)
                 (const ServerMovementReq *message,
                  void *closure_data);
typedef void (*ServerConnectionReq_Closure)
                 (const ServerConnectionReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    direction_enum__descriptor;
extern const ProtobufCEnumDescriptor    move_result__descriptor;
extern const ProtobufCEnumDescriptor    connection_result__descriptor;
extern const ProtobufCMessageDescriptor client_movement_req__descriptor;
extern const ProtobufCMessageDescriptor client_connection_req__descriptor;
extern const ProtobufCMessageDescriptor server_movement_req__descriptor;
extern const ProtobufCMessageDescriptor server_connection_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_5fcomms_2eproto__INCLUDED */
