/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message_comms.proto */

#ifndef PROTOBUF_C_message_5fcomms_2eproto__INCLUDED
#define PROTOBUF_C_message_5fcomms_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Color Color;
typedef struct Planet Planet;
typedef struct Trash Trash;
typedef struct Ship Ship;
typedef struct WorldState WorldState;
typedef struct ClientMovementReq ClientMovementReq;
typedef struct ClientConnectionReq ClientConnectionReq;
typedef struct ClientExitReq ClientExitReq;
typedef struct ServerMovementReq ServerMovementReq;
typedef struct ServerConnectionReq ServerConnectionReq;


/* --- enums --- */

typedef enum _DirectionEnum {
  DIRECTION_ENUM__UP = 0,
  DIRECTION_ENUM__DOWN = 1,
  DIRECTION_ENUM__LEFT = 2,
  DIRECTION_ENUM__RIGHT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIRECTION_ENUM)
} DirectionEnum;
typedef enum _MoveResult {
  MOVE_RESULT__OK = 0,
  MOVE_RESULT__WALL = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MOVE_RESULT)
} MoveResult;
typedef enum _ConnectionResult {
  CONNECTION_RESULT__CONN_OK = 0,
  CONNECTION_RESULT__CONN_ERROR = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CONNECTION_RESULT)
} ConnectionResult;

/* --- messages --- */

struct  Color
{
  ProtobufCMessage base;
  uint32_t r;
  uint32_t g;
  uint32_t b;
  uint32_t a;
};
#define COLOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&color__descriptor) \
, 0, 0, 0, 0 }


struct  Planet
{
  ProtobufCMessage base;
  char *name;
  int32_t x;
  int32_t y;
  int32_t trash;
  int32_t mass;
  Color *color;
};
#define PLANET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planet__descriptor) \
, NULL, 0, 0, 0, 0, NULL }


struct  Trash
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
  int32_t mass;
  Color *color;
  /*
   *  0 roaming, 1  on ship, 2 recicled
   */
  int32_t taken;
  char *ship_name;
};
#define TRASH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trash__descriptor) \
, 0, 0, 0, NULL, 0, NULL }


struct  Ship
{
  ProtobufCMessage base;
  float x;
  float y;
  char *name;
  /*
   *1 if using 0 if not
   */
  int32_t use;
  int32_t trash;
};
#define SHIP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ship__descriptor) \
, 0, 0, NULL, 0, 0 }


struct  WorldState
{
  ProtobufCMessage base;
  int32_t seq;
  size_t n_planets;
  Planet **planets;
  size_t n_trash;
  Trash **trash;
  size_t n_ships;
  Ship **ships;
};
#define WORLD_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&world_state__descriptor) \
, 0, 0,NULL, 0,NULL, 0,NULL }


struct  ClientMovementReq
{
  ProtobufCMessage base;
  char *type;
  ProtobufCBinaryData ch;
  int32_t pass;
  DirectionEnum dir;
};
extern char client_movement_req__type__default_value[];
#define CLIENT_MOVEMENT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_movement_req__descriptor) \
, client_movement_req__type__default_value, {0,NULL}, 0, DIRECTION_ENUM__UP }


struct  ClientConnectionReq
{
  ProtobufCMessage base;
  char *type;
};
extern char client_connection_req__type__default_value[];
#define CLIENT_CONNECTION_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_connection_req__descriptor) \
, client_connection_req__type__default_value }


struct  ClientExitReq
{
  ProtobufCMessage base;
  char *type;
  ProtobufCBinaryData ch;
  int32_t pass;
};
extern char client_exit_req__type__default_value[];
#define CLIENT_EXIT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_exit_req__descriptor) \
, client_exit_req__type__default_value, {0,NULL}, 0 }


struct  ServerMovementReq
{
  ProtobufCMessage base;
  MoveResult result;
};
#define SERVER_MOVEMENT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_movement_req__descriptor) \
, MOVE_RESULT__OK }


struct  ServerConnectionReq
{
  ProtobufCMessage base;
  ConnectionResult result;
  ProtobufCBinaryData name;
  int32_t pass;
};
#define SERVER_CONNECTION_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_connection_req__descriptor) \
, CONNECTION_RESULT__CONN_OK, {0,NULL}, 0 }


/* Color methods */
void   color__init
                     (Color         *message);
size_t color__get_packed_size
                     (const Color   *message);
size_t color__pack
                     (const Color   *message,
                      uint8_t             *out);
size_t color__pack_to_buffer
                     (const Color   *message,
                      ProtobufCBuffer     *buffer);
Color *
       color__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   color__free_unpacked
                     (Color *message,
                      ProtobufCAllocator *allocator);
/* Planet methods */
void   planet__init
                     (Planet         *message);
size_t planet__get_packed_size
                     (const Planet   *message);
size_t planet__pack
                     (const Planet   *message,
                      uint8_t             *out);
size_t planet__pack_to_buffer
                     (const Planet   *message,
                      ProtobufCBuffer     *buffer);
Planet *
       planet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planet__free_unpacked
                     (Planet *message,
                      ProtobufCAllocator *allocator);
/* Trash methods */
void   trash__init
                     (Trash         *message);
size_t trash__get_packed_size
                     (const Trash   *message);
size_t trash__pack
                     (const Trash   *message,
                      uint8_t             *out);
size_t trash__pack_to_buffer
                     (const Trash   *message,
                      ProtobufCBuffer     *buffer);
Trash *
       trash__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trash__free_unpacked
                     (Trash *message,
                      ProtobufCAllocator *allocator);
/* Ship methods */
void   ship__init
                     (Ship         *message);
size_t ship__get_packed_size
                     (const Ship   *message);
size_t ship__pack
                     (const Ship   *message,
                      uint8_t             *out);
size_t ship__pack_to_buffer
                     (const Ship   *message,
                      ProtobufCBuffer     *buffer);
Ship *
       ship__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ship__free_unpacked
                     (Ship *message,
                      ProtobufCAllocator *allocator);
/* WorldState methods */
void   world_state__init
                     (WorldState         *message);
size_t world_state__get_packed_size
                     (const WorldState   *message);
size_t world_state__pack
                     (const WorldState   *message,
                      uint8_t             *out);
size_t world_state__pack_to_buffer
                     (const WorldState   *message,
                      ProtobufCBuffer     *buffer);
WorldState *
       world_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   world_state__free_unpacked
                     (WorldState *message,
                      ProtobufCAllocator *allocator);
/* ClientMovementReq methods */
void   client_movement_req__init
                     (ClientMovementReq         *message);
size_t client_movement_req__get_packed_size
                     (const ClientMovementReq   *message);
size_t client_movement_req__pack
                     (const ClientMovementReq   *message,
                      uint8_t             *out);
size_t client_movement_req__pack_to_buffer
                     (const ClientMovementReq   *message,
                      ProtobufCBuffer     *buffer);
ClientMovementReq *
       client_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_movement_req__free_unpacked
                     (ClientMovementReq *message,
                      ProtobufCAllocator *allocator);
/* ClientConnectionReq methods */
void   client_connection_req__init
                     (ClientConnectionReq         *message);
size_t client_connection_req__get_packed_size
                     (const ClientConnectionReq   *message);
size_t client_connection_req__pack
                     (const ClientConnectionReq   *message,
                      uint8_t             *out);
size_t client_connection_req__pack_to_buffer
                     (const ClientConnectionReq   *message,
                      ProtobufCBuffer     *buffer);
ClientConnectionReq *
       client_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_connection_req__free_unpacked
                     (ClientConnectionReq *message,
                      ProtobufCAllocator *allocator);
/* ClientExitReq methods */
void   client_exit_req__init
                     (ClientExitReq         *message);
size_t client_exit_req__get_packed_size
                     (const ClientExitReq   *message);
size_t client_exit_req__pack
                     (const ClientExitReq   *message,
                      uint8_t             *out);
size_t client_exit_req__pack_to_buffer
                     (const ClientExitReq   *message,
                      ProtobufCBuffer     *buffer);
ClientExitReq *
       client_exit_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_exit_req__free_unpacked
                     (ClientExitReq *message,
                      ProtobufCAllocator *allocator);
/* ServerMovementReq methods */
void   server_movement_req__init
                     (ServerMovementReq         *message);
size_t server_movement_req__get_packed_size
                     (const ServerMovementReq   *message);
size_t server_movement_req__pack
                     (const ServerMovementReq   *message,
                      uint8_t             *out);
size_t server_movement_req__pack_to_buffer
                     (const ServerMovementReq   *message,
                      ProtobufCBuffer     *buffer);
ServerMovementReq *
       server_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_movement_req__free_unpacked
                     (ServerMovementReq *message,
                      ProtobufCAllocator *allocator);
/* ServerConnectionReq methods */
void   server_connection_req__init
                     (ServerConnectionReq         *message);
size_t server_connection_req__get_packed_size
                     (const ServerConnectionReq   *message);
size_t server_connection_req__pack
                     (const ServerConnectionReq   *message,
                      uint8_t             *out);
size_t server_connection_req__pack_to_buffer
                     (const ServerConnectionReq   *message,
                      ProtobufCBuffer     *buffer);
ServerConnectionReq *
       server_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_connection_req__free_unpacked
                     (ServerConnectionReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Color_Closure)
                 (const Color *message,
                  void *closure_data);
typedef void (*Planet_Closure)
                 (const Planet *message,
                  void *closure_data);
typedef void (*Trash_Closure)
                 (const Trash *message,
                  void *closure_data);
typedef void (*Ship_Closure)
                 (const Ship *message,
                  void *closure_data);
typedef void (*WorldState_Closure)
                 (const WorldState *message,
                  void *closure_data);
typedef void (*ClientMovementReq_Closure)
                 (const ClientMovementReq *message,
                  void *closure_data);
typedef void (*ClientConnectionReq_Closure)
                 (const ClientConnectionReq *message,
                  void *closure_data);
typedef void (*ClientExitReq_Closure)
                 (const ClientExitReq *message,
                  void *closure_data);
typedef void (*ServerMovementReq_Closure)
                 (const ServerMovementReq *message,
                  void *closure_data);
typedef void (*ServerConnectionReq_Closure)
                 (const ServerConnectionReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    direction_enum__descriptor;
extern const ProtobufCEnumDescriptor    move_result__descriptor;
extern const ProtobufCEnumDescriptor    connection_result__descriptor;
extern const ProtobufCMessageDescriptor color__descriptor;
extern const ProtobufCMessageDescriptor planet__descriptor;
extern const ProtobufCMessageDescriptor trash__descriptor;
extern const ProtobufCMessageDescriptor ship__descriptor;
extern const ProtobufCMessageDescriptor world_state__descriptor;
extern const ProtobufCMessageDescriptor client_movement_req__descriptor;
extern const ProtobufCMessageDescriptor client_connection_req__descriptor;
extern const ProtobufCMessageDescriptor client_exit_req__descriptor;
extern const ProtobufCMessageDescriptor server_movement_req__descriptor;
extern const ProtobufCMessageDescriptor server_connection_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_5fcomms_2eproto__INCLUDED */
