/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message_comms.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message_comms.pb-c.h"
void   color__init
                     (Color         *message)
{
  static const Color init_value = COLOR__INIT;
  *message = init_value;
}
size_t color__get_packed_size
                     (const Color *message)
{
  assert(message->base.descriptor == &color__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t color__pack
                     (const Color *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &color__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t color__pack_to_buffer
                     (const Color *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &color__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Color *
       color__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Color *)
     protobuf_c_message_unpack (&color__descriptor,
                                allocator, len, data);
}
void   color__free_unpacked
                     (Color *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &color__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planet__init
                     (Planet         *message)
{
  static const Planet init_value = PLANET__INIT;
  *message = init_value;
}
size_t planet__get_packed_size
                     (const Planet *message)
{
  assert(message->base.descriptor == &planet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planet__pack
                     (const Planet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planet__pack_to_buffer
                     (const Planet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planet *
       planet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planet *)
     protobuf_c_message_unpack (&planet__descriptor,
                                allocator, len, data);
}
void   planet__free_unpacked
                     (Planet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trash__init
                     (Trash         *message)
{
  static const Trash init_value = TRASH__INIT;
  *message = init_value;
}
size_t trash__get_packed_size
                     (const Trash *message)
{
  assert(message->base.descriptor == &trash__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trash__pack
                     (const Trash *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trash__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trash__pack_to_buffer
                     (const Trash *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trash__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Trash *
       trash__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Trash *)
     protobuf_c_message_unpack (&trash__descriptor,
                                allocator, len, data);
}
void   trash__free_unpacked
                     (Trash *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trash__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ship__init
                     (Ship         *message)
{
  static const Ship init_value = SHIP__INIT;
  *message = init_value;
}
size_t ship__get_packed_size
                     (const Ship *message)
{
  assert(message->base.descriptor == &ship__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ship__pack
                     (const Ship *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ship__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ship__pack_to_buffer
                     (const Ship *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ship__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ship *
       ship__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ship *)
     protobuf_c_message_unpack (&ship__descriptor,
                                allocator, len, data);
}
void   ship__free_unpacked
                     (Ship *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ship__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   world_state__init
                     (WorldState         *message)
{
  static const WorldState init_value = WORLD_STATE__INIT;
  *message = init_value;
}
size_t world_state__get_packed_size
                     (const WorldState *message)
{
  assert(message->base.descriptor == &world_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t world_state__pack
                     (const WorldState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &world_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t world_state__pack_to_buffer
                     (const WorldState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &world_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WorldState *
       world_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WorldState *)
     protobuf_c_message_unpack (&world_state__descriptor,
                                allocator, len, data);
}
void   world_state__free_unpacked
                     (WorldState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &world_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_movement_req__init
                     (ClientMovementReq         *message)
{
  static const ClientMovementReq init_value = CLIENT_MOVEMENT_REQ__INIT;
  *message = init_value;
}
size_t client_movement_req__get_packed_size
                     (const ClientMovementReq *message)
{
  assert(message->base.descriptor == &client_movement_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_movement_req__pack
                     (const ClientMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_movement_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_movement_req__pack_to_buffer
                     (const ClientMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_movement_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientMovementReq *
       client_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientMovementReq *)
     protobuf_c_message_unpack (&client_movement_req__descriptor,
                                allocator, len, data);
}
void   client_movement_req__free_unpacked
                     (ClientMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_movement_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_connection_req__init
                     (ClientConnectionReq         *message)
{
  static const ClientConnectionReq init_value = CLIENT_CONNECTION_REQ__INIT;
  *message = init_value;
}
size_t client_connection_req__get_packed_size
                     (const ClientConnectionReq *message)
{
  assert(message->base.descriptor == &client_connection_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_connection_req__pack
                     (const ClientConnectionReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_connection_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_connection_req__pack_to_buffer
                     (const ClientConnectionReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_connection_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientConnectionReq *
       client_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientConnectionReq *)
     protobuf_c_message_unpack (&client_connection_req__descriptor,
                                allocator, len, data);
}
void   client_connection_req__free_unpacked
                     (ClientConnectionReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_connection_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_exit_req__init
                     (ClientExitReq         *message)
{
  static const ClientExitReq init_value = CLIENT_EXIT_REQ__INIT;
  *message = init_value;
}
size_t client_exit_req__get_packed_size
                     (const ClientExitReq *message)
{
  assert(message->base.descriptor == &client_exit_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_exit_req__pack
                     (const ClientExitReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_exit_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_exit_req__pack_to_buffer
                     (const ClientExitReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_exit_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientExitReq *
       client_exit_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientExitReq *)
     protobuf_c_message_unpack (&client_exit_req__descriptor,
                                allocator, len, data);
}
void   client_exit_req__free_unpacked
                     (ClientExitReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_exit_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_movement_req__init
                     (ServerMovementReq         *message)
{
  static const ServerMovementReq init_value = SERVER_MOVEMENT_REQ__INIT;
  *message = init_value;
}
size_t server_movement_req__get_packed_size
                     (const ServerMovementReq *message)
{
  assert(message->base.descriptor == &server_movement_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_movement_req__pack
                     (const ServerMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_movement_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_movement_req__pack_to_buffer
                     (const ServerMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_movement_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerMovementReq *
       server_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerMovementReq *)
     protobuf_c_message_unpack (&server_movement_req__descriptor,
                                allocator, len, data);
}
void   server_movement_req__free_unpacked
                     (ServerMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_movement_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_connection_req__init
                     (ServerConnectionReq         *message)
{
  static const ServerConnectionReq init_value = SERVER_CONNECTION_REQ__INIT;
  *message = init_value;
}
size_t server_connection_req__get_packed_size
                     (const ServerConnectionReq *message)
{
  assert(message->base.descriptor == &server_connection_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_connection_req__pack
                     (const ServerConnectionReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_connection_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_connection_req__pack_to_buffer
                     (const ServerConnectionReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_connection_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerConnectionReq *
       server_connection_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerConnectionReq *)
     protobuf_c_message_unpack (&server_connection_req__descriptor,
                                allocator, len, data);
}
void   server_connection_req__free_unpacked
                     (ServerConnectionReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_connection_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor color__field_descriptors[4] =
{
  {
    "r",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Color, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Color, g),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Color, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Color, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned color__field_indices_by_name[] = {
  3,   /* field[3] = a */
  2,   /* field[2] = b */
  1,   /* field[1] = g */
  0,   /* field[0] = r */
};
static const ProtobufCIntRange color__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor color__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Color",
  "Color",
  "Color",
  "",
  sizeof(Color),
  4,
  color__field_descriptors,
  color__field_indices_by_name,
  1,  color__number_ranges,
  (ProtobufCMessageInit) color__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planet__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planet, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planet, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planet, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trash",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planet, trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mass",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planet, mass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planet, color),
    &color__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planet__field_indices_by_name[] = {
  5,   /* field[5] = color */
  4,   /* field[4] = mass */
  0,   /* field[0] = name */
  3,   /* field[3] = trash */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange planet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor planet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Planet",
  "Planet",
  "Planet",
  "",
  sizeof(Planet),
  6,
  planet__field_descriptors,
  planet__field_indices_by_name,
  1,  planet__number_ranges,
  (ProtobufCMessageInit) planet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trash__field_descriptors[6] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trash, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trash, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mass",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trash, mass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Trash, color),
    &color__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "taken",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trash, taken),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ship_name",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Trash, ship_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trash__field_indices_by_name[] = {
  3,   /* field[3] = color */
  2,   /* field[2] = mass */
  5,   /* field[5] = ship_name */
  4,   /* field[4] = taken */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange trash__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor trash__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Trash",
  "Trash",
  "Trash",
  "",
  sizeof(Trash),
  6,
  trash__field_descriptors,
  trash__field_indices_by_name,
  1,  trash__number_ranges,
  (ProtobufCMessageInit) trash__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ship__field_descriptors[5] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ship, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ship, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ship, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ship, use),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trash",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ship, trash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ship__field_indices_by_name[] = {
  2,   /* field[2] = name */
  4,   /* field[4] = trash */
  3,   /* field[3] = use */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange ship__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ship__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ship",
  "Ship",
  "Ship",
  "",
  sizeof(Ship),
  5,
  ship__field_descriptors,
  ship__field_indices_by_name,
  2,  ship__number_ranges,
  (ProtobufCMessageInit) ship__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor world_state__field_descriptors[4] =
{
  {
    "seq",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WorldState, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "planets",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WorldState, n_planets),
    offsetof(WorldState, planets),
    &planet__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trash",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WorldState, n_trash),
    offsetof(WorldState, trash),
    &trash__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ships",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WorldState, n_ships),
    offsetof(WorldState, ships),
    &ship__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned world_state__field_indices_by_name[] = {
  1,   /* field[1] = planets */
  0,   /* field[0] = seq */
  3,   /* field[3] = ships */
  2,   /* field[2] = trash */
};
static const ProtobufCIntRange world_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor world_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WorldState",
  "WorldState",
  "WorldState",
  "",
  sizeof(WorldState),
  4,
  world_state__field_descriptors,
  world_state__field_indices_by_name,
  1,  world_state__number_ranges,
  (ProtobufCMessageInit) world_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char client_movement_req__type__default_value[] = "MOVE";
static const ProtobufCFieldDescriptor client_movement_req__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, type),
    NULL,
    &client_movement_req__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, pass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dir",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientMovementReq, dir),
    &direction_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_movement_req__field_indices_by_name[] = {
  1,   /* field[1] = ch */
  3,   /* field[3] = dir */
  2,   /* field[2] = pass */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange client_movement_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor client_movement_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_movement_req",
  "ClientMovementReq",
  "ClientMovementReq",
  "",
  sizeof(ClientMovementReq),
  4,
  client_movement_req__field_descriptors,
  client_movement_req__field_indices_by_name,
  1,  client_movement_req__number_ranges,
  (ProtobufCMessageInit) client_movement_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char client_connection_req__type__default_value[] = "HELLO";
static const ProtobufCFieldDescriptor client_connection_req__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientConnectionReq, type),
    NULL,
    &client_connection_req__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_connection_req__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange client_connection_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_connection_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_connection_req",
  "ClientConnectionReq",
  "ClientConnectionReq",
  "",
  sizeof(ClientConnectionReq),
  1,
  client_connection_req__field_descriptors,
  client_connection_req__field_indices_by_name,
  1,  client_connection_req__number_ranges,
  (ProtobufCMessageInit) client_connection_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char client_exit_req__type__default_value[] = "EXIT";
static const ProtobufCFieldDescriptor client_exit_req__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientExitReq, type),
    NULL,
    &client_exit_req__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ClientExitReq, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ClientExitReq, pass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_exit_req__field_indices_by_name[] = {
  1,   /* field[1] = ch */
  2,   /* field[2] = pass */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange client_exit_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client_exit_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_exit_req",
  "ClientExitReq",
  "ClientExitReq",
  "",
  sizeof(ClientExitReq),
  3,
  client_exit_req__field_descriptors,
  client_exit_req__field_indices_by_name,
  1,  client_exit_req__number_ranges,
  (ProtobufCMessageInit) client_exit_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_movement_req__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerMovementReq, result),
    &move_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_movement_req__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange server_movement_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor server_movement_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "server_movement_req",
  "ServerMovementReq",
  "ServerMovementReq",
  "",
  sizeof(ServerMovementReq),
  1,
  server_movement_req__field_descriptors,
  server_movement_req__field_indices_by_name,
  1,  server_movement_req__number_ranges,
  (ProtobufCMessageInit) server_movement_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_connection_req__field_descriptors[3] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerConnectionReq, result),
    &connection_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerConnectionReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ServerConnectionReq, pass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_connection_req__field_indices_by_name[] = {
  1,   /* field[1] = name */
  2,   /* field[2] = pass */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange server_connection_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor server_connection_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "server_connection_req",
  "ServerConnectionReq",
  "ServerConnectionReq",
  "",
  sizeof(ServerConnectionReq),
  3,
  server_connection_req__field_descriptors,
  server_connection_req__field_indices_by_name,
  1,  server_connection_req__number_ranges,
  (ProtobufCMessageInit) server_connection_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction_enum__enum_values_by_number[4] =
{
  { "UP", "DIRECTION_ENUM__UP", 0 },
  { "DOWN", "DIRECTION_ENUM__DOWN", 1 },
  { "LEFT", "DIRECTION_ENUM__LEFT", 2 },
  { "RIGHT", "DIRECTION_ENUM__RIGHT", 3 },
};
static const ProtobufCIntRange direction_enum__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction_enum__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction_enum",
  "Direction_enum",
  "DirectionEnum",
  "",
  4,
  direction_enum__enum_values_by_number,
  4,
  direction_enum__enum_values_by_name,
  1,
  direction_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue move_result__enum_values_by_number[2] =
{
  { "OK", "MOVE_RESULT__OK", 0 },
  { "WALL", "MOVE_RESULT__WALL", 1 },
};
static const ProtobufCIntRange move_result__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex move_result__enum_values_by_name[2] =
{
  { "OK", 0 },
  { "WALL", 1 },
};
const ProtobufCEnumDescriptor move_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MoveResult",
  "MoveResult",
  "MoveResult",
  "",
  2,
  move_result__enum_values_by_number,
  2,
  move_result__enum_values_by_name,
  1,
  move_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue connection_result__enum_values_by_number[2] =
{
  { "CONN_OK", "CONNECTION_RESULT__CONN_OK", 0 },
  { "CONN_ERROR", "CONNECTION_RESULT__CONN_ERROR", 1 },
};
static const ProtobufCIntRange connection_result__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex connection_result__enum_values_by_name[2] =
{
  { "CONN_ERROR", 1 },
  { "CONN_OK", 0 },
};
const ProtobufCEnumDescriptor connection_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ConnectionResult",
  "ConnectionResult",
  "ConnectionResult",
  "",
  2,
  connection_result__enum_values_by_number,
  2,
  connection_result__enum_values_by_name,
  1,
  connection_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
